name: 休日実行のテスト
on:
  pull_request:
    types: [opened, reopened]
 
jobs:
  ##### 祝日かどうか確認 #####
  check_holiday:
    runs-on: ubuntu-22.04
    outputs:
        holiday: ${{ steps.is_holiday.outputs.holiday }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install @holiday-jp/holiday_jp
      - uses: actions/github-script@v7
        id: is_holiday
        with:
#          script: |
#            const holiday_jp = require(`${process.env.GITHUB_WORKSPACE}/node_modules/@holiday-jp/holiday_jp`)
#            core.setOutput('holiday', holiday_jp.isHoliday(new Date()));
#          script: |
#            const holiday_jp = require(`${process.env.GITHUB_WORKSPACE}/node_modules/@holiday-jp/holiday_jp`)
#            const jstDate = new Date(new Date().toLocaleString('en-US', { timeZone: 'Asia/Tokyo' }));
#            // JST日付をコンソールに出力
#            console.log("JST Date and Time: ", jstDate);
#            // 現在の日付をUTCでも出力して確認
#           console.log("UTC Date and Time: ", new Date());
#            
#            // 祝日かどうかの判定
#            const isHoliday = holiday_jp.isHoliday(jstDate);
#            
#            // 判定結果を出力
#            console.log("Is Holiday: ", isHoliday);
#
#            core.setOutput('holiday', holiday_jp.isHoliday(jstDate));
# 前日が祝日の時の検証
          script: |
            const holiday_jp = require(`${process.env.GITHUB_WORKSPACE}/node_modules/@holiday-jp/holiday_jp`);
            const yesterday = new Date();
            yesterday.setDate(yesterday.getDate() - 4); // 日付を1日減らして「昨日」にする
            const jstDate = new Date(yesterday.toLocaleString('en-US', { timeZone: 'Asia/Tokyo' }));
            
            // 日付を標準出力に表示
            console.log("JST Date and Time: ", jstDate);

            // 昨日が祝日かどうかを確認
            const isHoliday = holiday_jp.isHoliday(jstDate);
            console.log(`昨日は祝日か: ${isHoliday}`);
            
            // 結果をセット
            core.setOutput('holiday', isHoliday);

  ##### 後続ジョブ #####
  subsequent_job:
    needs: check_holiday
    if: needs.check_holiday.outputs.holiday != 'true'
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: ls job
        run: ls -alt
      - name: Debug holiday output
        run: echo "Holiday output ${{ needs.check_holiday.outputs.holiday }}"
