name: 休日実行のテスト
on:
  pull_request:
    types: [opened, reopened]
 
jobs:
  ##### 祝日かどうか確認 #####
  check_holiday:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install @holiday-jp/holiday_jp
      - uses: actions/github-script@v7
        id: is_holiday
        with:
#          script: |
#            const holiday_jp = require(`${process.env.GITHUB_WORKSPACE}/node_modules/@holiday-jp/holiday_jp`)
#            core.setOutput('holiday', holiday_jp.isHoliday(new Date()));
          script: |
            const holiday_jp = require(`${process.env.GITHUB_WORKSPACE}/node_modules/@holiday-jp/holiday_jp`);
            const yesterday = new Date();
            yesterday.setDate(yesterday.getDate() - 1); // 日付を1日減らして「昨日」にする
            core.setOutput('holiday', holiday_jp.isHoliday(yesterday));

  ##### 後続ジョブ #####
  subsequent_job:
    needs: [check_holiday]
    if: needs.check_holiday.outputs.holiday != 'true'
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: ls job
        run: ls -alt
