name: 休日実行のテスト
on:
  pull_request:
    types: [opened, reopened]
 
jobs:
  ##### 祝日かどうか確認 #####
  check_holiday:
    runs-on: ubuntu-22.04
    outputs:
        holiday: ${{ steps.is_holiday.outputs.holiday }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install @holiday-jp/holiday_jp
      - uses: actions/github-script@v7
        id: is_holiday
        with:
          script: |
            const holiday_jp = require(`${process.env.GITHUB_WORKSPACE}/node_modules/@holiday-jp/holiday_jp`)
            core.setOutput('holiday', holiday_jp.isHoliday(new Date()));
# 前日が祝日の時の検証
#          script: |
#            const holiday_jp = require(`${process.env.GITHUB_WORKSPACE}/node_modules/@holiday-jp/holiday_jp`);
#            const yesterday = new Date();
#            yesterday.setDate(yesterday.getDate() - 1); // 日付を1日減らして「昨日」にする

#            // 日付を標準出力に表示
#            console.log(`昨日の日付: ${yesterday.toISOString()}`);

#            // 昨日が祝日かどうかを確認
#            const isHoliday = holiday_jp.isHoliday(yesterday);
#            console.log(`昨日は祝日か: ${isHoliday}`);

#            // 結果をセット
#            core.setOutput('holiday', isHoliday);

  ##### 後続ジョブ #####
  subsequent_job:
    needs: check_holiday
    if: needs.check_holiday.outputs.holiday != 'true'
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: ls job
        run: ls -alt
      - name: Debug holiday output
        run: echo "Holiday output ${{ needs.check_holiday.outputs.holiday }}"
